### PR TITLE
Correct invalid default tmsUpload.namedUser

### PR DESCRIPTION
**Pull request by laszloKajan**
tmsUpload.nameUser must conform to these requirements as reported by the TMService API:

> {"message":"Request validation failed with 1 error(s): [Error in field: \u0027namedUser\u0027: \u0027Only Latin letters, numbers and following characters are allowed: \u0027_.-+\u0027, maximal length 60 characters\u0027; rejected value: \u0027CLOUD SDK PIPELINE\u0027]","errorType":"com.sap.lm.sl.alm.ts.core.exception.service.TsValidationException"}

The default should set a correct namedUser, e.g. 'CLOUD_SDK_PIPELINE'.

## Context

Set a correct default tmsUpload.namedUser.

## Definition of Done
Please consider all items and remove only if not applicable.

- [*] I carefully reviewed my own pull request before assigning someone.
- [*] Changes to the configuration are also documented in the [configuration.md](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md)
- [-] Pipeline config schema is updated [in schema store](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/cloud-sdk-pipeline-config-schema.json)
- [-] The [feature matrix](https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/doc/pipeline/build-tools.md#feature-matrix) is updated, if a new feature is added for one of the build tools
- [-] Important design decisions are documented as an [ADR](https://github.com/SAP/cloud-s4-sdk-pipeline/tree/master/doc/architecture/decisions)
- [-] This change is operations-relevant and I have updated the operations guide correspondingly
- [-] There are tests covering this change

## Merging
Please use squash merge and provide a good commit message, e.g. inspired by the context above. 
Make sure to remove the reference to this pull request and that this template is not part of the commit message.
Also, please ensure the commit message is not just a list of "WIP" commit messages.

### CODE REVIEW

**Comment by laszloKajan** [comment]
@daniel-kurzynski @fwilhe Dear Daniel and Florian!
Could you please review this pull request?
Thank you in advance.
Best regards,
Laszlo Kajan

**Comment by fwilhe** [comment]
Hi @laszloKajan 

thanks for your contribution. Due to our process I can't directly merge your PR here, but I've triggered the process to merge your change.

**Comment by fwilhe** [comment]
Fixed in https://github.com/SAP/cloud-s4-sdk-pipeline-lib/commit/ea3644dfca79b75341938925721677db556bb27f (I'm sorry the attribution got lost in the process, I tried to preserve it)

**Comment by laszloKajan** [comment]
Thank you, Florian!

**Pull request closed without merging**
